<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Module 4.5 – DATS 1001–Fall Schedule</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/ds4all-logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-f428fda71a3abb5b1b9c21151da8fd61.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-6ec1ea2183979a90750e7180bf9040de.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-f428fda71a3abb5b1b9c21151da8fd61.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-8ba55214e2cf2b8151fd22e466944314.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-72ecc774e5eb6ee2146fcd9ff417b5a6.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-8ba55214e2cf2b8151fd22e466944314.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<meta property="og:title" content="Module 4.5 – DATS 1001–Fall Schedule">
<meta property="og:description" content="Model Selection">
<meta property="og:site_name" content="DATS 1001--Fall Schedule">
<meta name="twitter:title" content="Module 4.5 – DATS 1001–Fall Schedule">
<meta name="twitter:description" content="Model Selection">
<meta name="twitter:card" content="summary">
</head>
<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Module 4.5</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../images/ds4all-logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none"></a>
      <div class="sidebar-tools-main tools-wide">
    <a href="https://blackboard.gwu.edu" title="Blackboard" class="quarto-navigation-tool px-1" aria-label="Blackboard"><i class="bi bi-mortarboard-fill"></i></a>
    <a href="https://library.gwu.edu/work-data" title="Gelman Data Services" class="quarto-navigation-tool px-1" aria-label="Gelman Data Services"><i class="bi bi-bar-chart-fill"></i></a>
    <a href="https://posit.cloud" title="Access R and RStudio" class="quarto-navigation-tool px-1" aria-label="Access R and RStudio"><i class="bi bi-r-circle"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Course information</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../course-description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Description</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../course-syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../course-support.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Support</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../instructor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Instructor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../course-links.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Useful links</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../faq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">FAQ</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Coding Asignments</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/coding-assignment-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/coding-assignment-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/coding-assignment-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/coding-assignment-4.qmd" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 4</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Project</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../project/project-assignment-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../project/project-assignment-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../project/project-assignment-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../project/project-datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datasets</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Weekly materials</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week-4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 4</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li>
<a href="#model-evaluation-criteria" id="toc-model-evaluation-criteria" class="nav-link" data-scroll-target="#model-evaluation-criteria">Model Evaluation Criteria</a>
  <ul class="collapse">
<li><a href="#adjusted-r-squared" id="toc-adjusted-r-squared" class="nav-link" data-scroll-target="#adjusted-r-squared">Adjusted R-squared</a></li>
  <li><a href="#akaike-information-criterion-aic" id="toc-akaike-information-criterion-aic" class="nav-link" data-scroll-target="#akaike-information-criterion-aic">Akaike Information Criterion (AIC)</a></li>
  <li><a href="#p-values-as-selection-criteria" id="toc-p-values-as-selection-criteria" class="nav-link" data-scroll-target="#p-values-as-selection-criteria">P-values as Selection Criteria</a></li>
  </ul>
</li>
  <li>
<a href="#automated-stepwise-selection" id="toc-automated-stepwise-selection" class="nav-link" data-scroll-target="#automated-stepwise-selection">Automated Stepwise Selection</a>
  <ul class="collapse">
<li><a href="#forward-selection" id="toc-forward-selection" class="nav-link" data-scroll-target="#forward-selection">Forward Selection</a></li>
  <li><a href="#backward-elimination" id="toc-backward-elimination" class="nav-link" data-scroll-target="#backward-elimination">Backward Elimination</a></li>
  <li><a href="#bidirectional-selection" id="toc-bidirectional-selection" class="nav-link" data-scroll-target="#bidirectional-selection">Bidirectional Selection</a></li>
  </ul>
</li>
  <li><a href="#incorporating-domain-knowledge" id="toc-incorporating-domain-knowledge" class="nav-link" data-scroll-target="#incorporating-domain-knowledge">Incorporating Domain Knowledge</a></li>
  <li>
<a href="#additional-methodological-considerations" id="toc-additional-methodological-considerations" class="nav-link" data-scroll-target="#additional-methodological-considerations">Additional Methodological Considerations</a>
  <ul class="collapse">
<li><a href="#multicollinearity" id="toc-multicollinearity" class="nav-link" data-scroll-target="#multicollinearity">Multicollinearity</a></li>
  <li><a href="#sample-size-requirements" id="toc-sample-size-requirements" class="nav-link" data-scroll-target="#sample-size-requirements">Sample Size Requirements</a></li>
  <li><a href="#model-validation" id="toc-model-validation" class="nav-link" data-scroll-target="#model-validation">Model Validation</a></li>
  </ul>
</li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/eteitelbaum/dats1001-summer/edit/main/modules/module-4.5.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/eteitelbaum/dats1001-summer/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Module 4.5</h1>
<p class="subtitle lead">Model Selection</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prework
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Install the <code>olsrr</code> package: <code>install.packages("olsrr")</code> and read the documentation pertaining to <a href="https://olsrr.rsquaredacademy.com/articles/variable_selection#introduction">variable selection</a>
</li>
<li>Run the following code to get set up for this module:</li>
</ul>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://creativecommons.org/licenses/by-sa/4.0/">vdemlite</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Load V-Dem data for 2019</span></span>
<span><span class="va">model_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://eteitelbaum.github.io/vdemlite/reference/fetchdem.html">fetchdem</a></span><span class="op">(</span></span>
<span>  indicators <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="st">"v2x_libdem"</span>, </span>
<span>  <span class="st">"e_gdppc"</span>, </span>
<span>  <span class="st">"v2cacamps"</span>,</span>
<span>  <span class="st">"v2x_gender"</span>,</span>
<span>  <span class="st">"v2x_corr"</span>,</span>
<span>  <span class="st">"e_regionpol_6C"</span><span class="op">)</span>,</span>
<span>  start_year <span class="op">=</span> <span class="fl">2006</span>, </span>
<span>  end_year <span class="op">=</span> <span class="fl">2006</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span></span>
<span>    country <span class="op">=</span> <span class="va">country_name</span>, </span>
<span>    lib_dem <span class="op">=</span> <span class="va">v2x_libdem</span>, </span>
<span>    wealth <span class="op">=</span> <span class="va">e_gdppc</span>,</span>
<span>    polarization <span class="op">=</span> <span class="va">v2cacamps</span>,</span>
<span>    women_empowerment <span class="op">=</span> <span class="va">v2x_gender</span>,</span>
<span>    corruption <span class="op">=</span> <span class="va">v2x_corr</span>,</span>
<span>    region <span class="op">=</span> <span class="va">e_regionpol_6C</span></span>
<span>    <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    region <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span></span>
<span>    <span class="va">region</span>,</span>
<span>    labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>      <span class="st">"Eastern Europe"</span>, </span>
<span>      <span class="st">"Latin America"</span>, </span>
<span>      <span class="st">"MENA"</span>, </span>
<span>      <span class="st">"Sub-Saharan Africa"</span>, </span>
<span>      <span class="st">"Western Europe &amp; North America"</span>, </span>
<span>      <span class="st">"Asia &amp; Pacific"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    log_wealth <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">wealth</span><span class="op">)</span> <span class="co"># have to manually log-transform wealth for olsrr</span></span>
<span>    <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="va">lib_dem</span><span class="op">:</span><span class="va">region</span><span class="op">)</span> <span class="co"># remove missing values for olsrr</span></span>
<span></span>
<span><span class="co">#glimpse(model_data)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
</div>
<section id="overview" class="level2"><h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>Now that we know how to run a regression we can talk about how to select the best model. In this module, we will explore the process of <strong>model selection</strong> in multiple regression contexts. Model selection involves choosing which predictor variables to include in a regression model to best explain the outcome variable while balancing complexity and interpretability.</p>
<p>This decision process involves navigating the fundamental <strong>bias-variance tradeoff</strong> in statistical modeling. Including more predictors can reduce bias by capturing important relationships between variables and the outcome. However, additional predictors also increase model variance by making the model more susceptible to overfitting to the specific sample under study. Conversely, models with fewer predictors may exhibit reduced variance but increased bias through the omission of important explanatory variables.</p>
<p>Several approaches can guide variable selection decisions. <em>Theory-driven selection</em> incorporates variables based on theoretical understanding of the phenomenon under investigation based on domain expertise. <em>Statistical criteria</em> employ measures such as AIC, BIC, or adjusted R-squared to balance model fit against complexity. <em>Cross-validation</em> assesses model performance on held-out data to evaluate generalizability.</p>
<p>Multiple regression modeling also requires consideration of several methodological concerns. <strong>Multicollinearity</strong> occurs when predictor variables exhibit high correlations with one another, complicating the separation of individual variable effects. <strong>Overfitting</strong> represents the tendency for models to fit training data too closely, resulting in poor generalization to new observations. Additionally, complex models present interpretation challenges, and larger numbers of predictors necessitate correspondingly larger sample sizes for reliable parameter estimation.</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/4pgaVtVBVjk?si=Wq93tjXuVj42s4Yf" title="Principles of Model Selection" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</section><section id="model-evaluation-criteria" class="level2"><h2 class="anchored" data-anchor-id="model-evaluation-criteria">Model Evaluation Criteria</h2>
<p>Model selection procedures require criteria for comparing alternative specifications. Each criterion approaches the balance between model fit and complexity differently, leading to potentially different optimal models.</p>
<section id="adjusted-r-squared" class="level3"><h3 class="anchored" data-anchor-id="adjusted-r-squared">Adjusted R-squared</h3>
<p>Adjusted R-squared addresses a fundamental limitation of regular R-squared: the tendency for R-squared to increase mechanically with the addition of any predictor variable, regardless of that variable’s true explanatory value. The adjusted R-squared applies a penalty for additional parameters according to the formula:</p>
<p><span class="math display">\[R_{adj}^2 = 1 - \frac{(1 - R^2)(n - 1)}{n - k - 1}\]</span></p>
<p>where <span class="math inline">\(n\)</span> represents the number of observations and <span class="math inline">\(k\)</span> represents the number of predictor variables. Higher adjusted R-squared values indicate superior model performance, as they reflect greater explained variance while accounting for model complexity.</p>
</section><section id="akaike-information-criterion-aic" class="level3"><h3 class="anchored" data-anchor-id="akaike-information-criterion-aic">Akaike Information Criterion (AIC)</h3>
<p>The Akaike Information Criterion provides an alternative approach to model evaluation grounded in information theory. AIC balances model fit against complexity through the formula:</p>
<p><span class="math display">\[AIC = -2(\text{log-likelihood}) + 2k\]</span></p>
<p>where <span class="math inline">\(k\)</span> represents the number of parameters (including predictors and intercept) and log-likelihood measures model fit to the observed data. <strong>Lower AIC values indicate superior models</strong>, representing the opposite interpretation from R-squared measures. AIC typically favors slightly more complex models than adjusted R-squared due to its lighter penalty structure for additional parameters.</p>
</section><section id="p-values-as-selection-criteria" class="level3"><h3 class="anchored" data-anchor-id="p-values-as-selection-criteria">P-values as Selection Criteria</h3>
<p>Recall that p-values represent the probability of observing a test statistic as extreme or more extreme than what was actually observed, assuming the null hypothesis is true. In regression contexts, p-values test whether individual regression coefficients differ significantly from zero. p-values have historically been employed in variable selection procedures, with common approaches involving the removal of variables with p-values exceeding predetermined thresholds (typically 0.05 or 0.10).</p>
<p>However, p-value-based variable selection introduces important methodological concerns. Stepwise selection increases the risk of a <strong>false positive</strong> (Type 1 error) by overfitting to noise. In the standard hypothesis testing framework featuring a five percent critical value, one out of 20 tests will yield a statistically significant result purely by chance. This risk is compounded in stepwise selection procedures that test multiple variables sequentially, as each test increases the likelihood of identifying spurious relationships.</p>
<p>Stepwise regression can also lead to <strong>false negatives</strong> (Type II error) by excluding variables that may have substantive theoretical importance but appear non-significant in intermediate steps.</p>
<p>Another concern is <strong>post-selection inference bias</strong> resulting from the fact that the same data are used both to select the model and to conduct inference. In this context, the reported p-values and confidence intervals no longer reflect valid hypothesis tests as they understate the true uncertainty associated with the selected model.</p>
<p>These limitations suggest that p-value-based selection should be approached with considerable caution, particularly compared to criteria like adjusted R-squared or AIC that explicitly account for the model selection process and do not suffer from the same multiple testing problems.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Modern Approaches to Model Selection
</div>
</div>
<div class="callout-body-container callout-body">
<p>While stepwise selection remains widely employed, contemporary statistical practice increasingly favors alternative approaches that address some limitations of traditional methods.</p>
<p><strong>Regularization methods</strong> such as LASSO and Ridge regression incorporate variable selection directly into the model fitting process. These techniques apply penalties to coefficient magnitudes, automatically shrinking less important predictors toward zero.</p>
<p><strong>Cross-validation</strong> approaches evaluate model performance through systematic partitioning of data into training and testing subsets. This strategy provides more reliable assessments of generalizability compared to information criteria calculated on the same data used for model fitting.</p>
<p><strong>Ensemble methods</strong> acknowledge model uncertainty by averaging predictions across multiple plausible models rather than selecting a single optimal specification. These approaches often demonstrate superior predictive performance compared to any individual model.</p>
<p>These advanced techniques are important to be aware of even though they exceed the scope of introductory regression courses.</p>
</div>
</div>
</section></section><section id="automated-stepwise-selection" class="level2"><h2 class="anchored" data-anchor-id="automated-stepwise-selection">Automated Stepwise Selection</h2>
<p>Automated selection procedures can systematically implement variable selection strategies. This section demonstrates these approaches using data from the Varieties of Democracy (V-Dem) project to predict liberal democracy scores across countries.</p>
<p>The analysis begins with estimation of a full model incorporating all available predictors:</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">full_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">lib_dem</span> <span class="op">~</span> <span class="va">log_wealth</span> <span class="op">+</span> <span class="va">polarization</span> <span class="op">+</span> <span class="va">women_empowerment</span> <span class="op">+</span> </span>
<span>                 <span class="va">corruption</span> <span class="op">+</span> <span class="va">region</span>, data <span class="op">=</span> <span class="va">model_data</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">full_model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lib_dem ~ log_wealth + polarization + women_empowerment + 
    corruption + region, data = model_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.43252 -0.06331  0.00253  0.07402  0.26311 

Coefficients:
                                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                           0.125962   0.093258   1.351   0.1787    
log_wealth                           -0.001450   0.014026  -0.103   0.9178    
polarization                         -0.009154   0.008323  -1.100   0.2730    
women_empowerment                     0.640860   0.072556   8.833 1.61e-15 ***
corruption                           -0.344607   0.055068  -6.258 3.35e-09 ***
regionLatin America                   0.062175   0.033837   1.837   0.0680 .  
regionMENA                           -0.004997   0.043303  -0.115   0.9083    
regionSub-Saharan Africa             -0.011206   0.034987  -0.320   0.7491    
regionWestern Europe &amp; North America  0.109096   0.039341   2.773   0.0062 ** 
regionAsia &amp; Pacific                 -0.029083   0.036100  -0.806   0.4216    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1228 on 162 degrees of freedom
Multiple R-squared:  0.8055,    Adjusted R-squared:  0.7947 
F-statistic: 74.55 on 9 and 162 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The full model achieves an adjusted R-squared of 0.795, indicating that approximately 79.5 percent of the variance in democracy scores can be explained by the included predictors.</p>
<section id="forward-selection" class="level3"><h3 class="anchored" data-anchor-id="forward-selection">Forward Selection</h3>
<p>Forward selection begins with an intercept-only model and sequentially adds predictors. At each step, the procedure selects the variable that produces the greatest improvement in the chosen criterion (adjusted R-squared in this example):</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://olsrr.rsquaredacademy.com/">olsrr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">forward_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://olsrr.rsquaredacademy.com/reference/ols_step_forward_adj_r2.html">ols_step_forward_adj_r2</a></span><span class="op">(</span><span class="va">full_model</span><span class="op">)</span></span>
<span></span>
<span><span class="va">forward_model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                                  Stepwise Summary                                   
-----------------------------------------------------------------------------------
Step    Variable               AIC         SBC         SBIC        R2       Adj. R2 
-----------------------------------------------------------------------------------
 0      Base Model             41.896      48.191    -449.065    0.00000    0.00000 
 1      women_empowerment    -131.886    -122.444    -622.069    0.64012    0.63801 
 2      corruption           -217.702    -205.112    -706.085    0.78402    0.78146 
 3      region               -224.442    -196.115    -720.133    0.80405    0.79568 
 4      polarization         -223.726    -192.251    -719.231    0.80550    0.79596 
-----------------------------------------------------------------------------------

Final Model Output 
------------------

                         Model Summary                           
----------------------------------------------------------------
R                       0.897       RMSE                  0.119 
R-Squared               0.806       MSE                   0.014 
Adj. R-Squared          0.796       Coef. Var            29.792 
Pred R-Squared          0.782       AIC                -223.726 
MAE                     0.090       SBC                -192.251 
----------------------------------------------------------------
 RMSE: Root Mean Square Error 
 MSE: Mean Square Error 
 MAE: Mean Absolute Error 
 AIC: Akaike Information Criteria 
 SBC: Schwarz Bayesian Criteria 

                               ANOVA                                 
--------------------------------------------------------------------
               Sum of                                               
              Squares         DF    Mean Square      F         Sig. 
--------------------------------------------------------------------
Regression     10.111          8          1.264    84.382    0.0000 
Residual        2.441        163          0.015                     
Total          12.553        171                                    
--------------------------------------------------------------------

                                               Parameter Estimates                                                
-----------------------------------------------------------------------------------------------------------------
                               model      Beta    Std. Error    Std. Beta      t        Sig      lower     upper 
-----------------------------------------------------------------------------------------------------------------
                         (Intercept)     0.120         0.076                  1.580    0.116    -0.030     0.271 
                   women_empowerment     0.641         0.072        0.471     8.898    0.000     0.499     0.784 
                          corruption    -0.342         0.047       -0.387    -7.214    0.000    -0.435    -0.248 
                 regionLatin America     0.063         0.033        0.082     1.871    0.063    -0.003     0.129 
                          regionMENA    -0.005         0.043       -0.006    -0.128    0.899    -0.090     0.079 
            regionSub-Saharan Africa    -0.009         0.030       -0.016    -0.311    0.756    -0.069     0.050 
regionWestern Europe &amp; North America     0.109         0.039        0.139     2.796    0.006     0.032     0.185 
                regionAsia &amp; Pacific    -0.028         0.035       -0.038    -0.811    0.418    -0.096     0.040 
                        polarization    -0.009         0.008       -0.045    -1.105    0.271    -0.026     0.007 
-----------------------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>The forward selection results demonstrate the sequential addition process. Women’s empowerment enters first due to its highest individual contribution to adjusted R-squared, followed by corruption control, with the process continuing until no remaining variables provide meaningful improvements to model fit.</p>
</section><section id="backward-elimination" class="level3"><h3 class="anchored" data-anchor-id="backward-elimination">Backward Elimination</h3>
<p>Backward elimination employs the opposite strategy, beginning with the full model and sequentially removing predictors. At each step, the procedure eliminates the variable whose removal least deteriorates model performance:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">backward_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://olsrr.rsquaredacademy.com/reference/ols_step_backward_adj_r2.html">ols_step_backward_adj_r2</a></span><span class="op">(</span><span class="va">full_model</span><span class="op">)</span></span>
<span></span>
<span><span class="va">backward_model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                               Stepwise Summary                               
----------------------------------------------------------------------------
Step    Variable        AIC         SBC         SBIC        R2       Adj. R2 
----------------------------------------------------------------------------
 0      Full Model    -221.737    -187.115    -717.119    0.80552    0.79471 
 1      log_wealth    -223.726    -192.251    -719.294    0.80550    0.79596 
----------------------------------------------------------------------------

Final Model Output 
------------------

                         Model Summary                           
----------------------------------------------------------------
R                       0.897       RMSE                  0.119 
R-Squared               0.806       MSE                   0.014 
Adj. R-Squared          0.796       Coef. Var            29.792 
Pred R-Squared          0.782       AIC                -223.726 
MAE                     0.090       SBC                -192.251 
----------------------------------------------------------------
 RMSE: Root Mean Square Error 
 MSE: Mean Square Error 
 MAE: Mean Absolute Error 
 AIC: Akaike Information Criteria 
 SBC: Schwarz Bayesian Criteria 

                               ANOVA                                 
--------------------------------------------------------------------
               Sum of                                               
              Squares         DF    Mean Square      F         Sig. 
--------------------------------------------------------------------
Regression     10.111          8          1.264    84.382    0.0000 
Residual        2.441        163          0.015                     
Total          12.553        171                                    
--------------------------------------------------------------------

                                               Parameter Estimates                                                
-----------------------------------------------------------------------------------------------------------------
                               model      Beta    Std. Error    Std. Beta      t        Sig      lower     upper 
-----------------------------------------------------------------------------------------------------------------
                         (Intercept)     0.120         0.076                  1.580    0.116    -0.030     0.271 
                        polarization    -0.009         0.008       -0.045    -1.105    0.271    -0.026     0.007 
                   women_empowerment     0.641         0.072        0.471     8.898    0.000     0.499     0.784 
                          corruption    -0.342         0.047       -0.387    -7.214    0.000    -0.435    -0.248 
                 regionLatin America     0.063         0.033        0.082     1.871    0.063    -0.003     0.129 
                          regionMENA    -0.005         0.043       -0.006    -0.128    0.899    -0.090     0.079 
            regionSub-Saharan Africa    -0.009         0.030       -0.016    -0.311    0.756    -0.069     0.050 
regionWestern Europe &amp; North America     0.109         0.039        0.139     2.796    0.006     0.032     0.185 
                regionAsia &amp; Pacific    -0.028         0.035       -0.038    -0.811    0.418    -0.096     0.040 
-----------------------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
</section><section id="bidirectional-selection" class="level3"><h3 class="anchored" data-anchor-id="bidirectional-selection">Bidirectional Selection</h3>
<p>Bidirectional selection combines forward and backward approaches, allowing both addition and removal of variables at each step. This method can potentially identify optimal models that pure forward or backward procedures might miss:</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">both_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://olsrr.rsquaredacademy.com/reference/ols_step_both_adj_r2.html">ols_step_both_adj_r2</a></span><span class="op">(</span><span class="va">full_model</span><span class="op">)</span></span>
<span></span>
<span><span class="va">both_model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                                    Stepwise Summary                                     
---------------------------------------------------------------------------------------
Step    Variable                   AIC         SBC         SBIC        R2       Adj. R2 
---------------------------------------------------------------------------------------
 0      Base Model                 41.896      48.191    -449.065    0.00000    0.00000 
 1      women_empowerment (+)    -131.886    -122.444    -622.069    0.64012    0.63801 
 2      corruption (+)           -217.702    -205.112    -706.085    0.78402    0.78146 
 3      region (+)               -224.442    -196.115    -720.133    0.80405    0.79568 
 4      polarization (+)         -223.726    -192.251    -719.231    0.80550    0.79596 
---------------------------------------------------------------------------------------

Final Model Output 
------------------

                         Model Summary                           
----------------------------------------------------------------
R                       0.897       RMSE                  0.119 
R-Squared               0.806       MSE                   0.014 
Adj. R-Squared          0.796       Coef. Var            29.792 
Pred R-Squared          0.782       AIC                -223.726 
MAE                     0.090       SBC                -192.251 
----------------------------------------------------------------
 RMSE: Root Mean Square Error 
 MSE: Mean Square Error 
 MAE: Mean Absolute Error 
 AIC: Akaike Information Criteria 
 SBC: Schwarz Bayesian Criteria 

                               ANOVA                                 
--------------------------------------------------------------------
               Sum of                                               
              Squares         DF    Mean Square      F         Sig. 
--------------------------------------------------------------------
Regression     10.111          8          1.264    84.382    0.0000 
Residual        2.441        163          0.015                     
Total          12.553        171                                    
--------------------------------------------------------------------

                                               Parameter Estimates                                                
-----------------------------------------------------------------------------------------------------------------
                               model      Beta    Std. Error    Std. Beta      t        Sig      lower     upper 
-----------------------------------------------------------------------------------------------------------------
                         (Intercept)     0.120         0.076                  1.580    0.116    -0.030     0.271 
                   women_empowerment     0.641         0.072        0.471     8.898    0.000     0.499     0.784 
                          corruption    -0.342         0.047       -0.387    -7.214    0.000    -0.435    -0.248 
                 regionLatin America     0.063         0.033        0.082     1.871    0.063    -0.003     0.129 
                          regionMENA    -0.005         0.043       -0.006    -0.128    0.899    -0.090     0.079 
            regionSub-Saharan Africa    -0.009         0.030       -0.016    -0.311    0.756    -0.069     0.050 
regionWestern Europe &amp; North America     0.109         0.039        0.139     2.796    0.006     0.032     0.185 
                regionAsia &amp; Pacific    -0.028         0.035       -0.038    -0.811    0.418    -0.096     0.040 
                        polarization    -0.009         0.008       -0.045    -1.105    0.271    -0.026     0.007 
-----------------------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>Comparison of the full and stepwise-selected models reveals how little changes in explanatory power despite model simplification. The adjusted R-squared for the full model is 0.7947, while the adjusted R-squared for the model selected via stepwise procedures is 0.796. At the same time, the number of predictors decreases slightly, from 9 in the full model to 8 in the selected model.</p>
<p>This minimal difference in fit highlights an important point: variable selection procedures may reduce complexity but often yield models with similar performance. This highlights the relevance of domain expertise in making meaningful modeling decisions.</p>
</section></section><section id="incorporating-domain-knowledge" class="level2"><h2 class="anchored" data-anchor-id="incorporating-domain-knowledge">Incorporating Domain Knowledge</h2>
<p>Statistical criteria alone provide insufficient guidance for model specification. Substantive theory and domain expertise must inform variable selection decisions. In democracy research, certain variables maintain theoretical importance regardless of their statistical significance in particular samples.</p>
<p>For example, <em>modernization theory</em> establishes wealth (GDP per capita) as a fundamental predictor of democratic development while comparative political analysis routinely includes regional controls to account for spatial diffusion effects and shared historical experiences.</p>
<p>In this scenario, we have strong reasons to believe that wealth and region are important predictors of democracy. We are, in other words, developing our model based on our <strong>theoretical understanding</strong> of the world, rather than simply relying on statistical criteria. Or, another way of stating it is that we are basing our model on our <strong>hypotheses</strong> about the outcome in question, rather than simply relying on statistical criteria.</p>
<p>To this end, the <code>olsrr</code> package accommodates theoretical constraints through the <code>include</code> argument, which forces retention of specified variables throughout the selection process:</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">theory_guided_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://olsrr.rsquaredacademy.com/reference/ols_step_both_adj_r2.html">ols_step_both_adj_r2</a></span><span class="op">(</span><span class="va">full_model</span>, include <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"log_wealth"</span>, <span class="st">"region"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">theory_guided_model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                                    Stepwise Summary                                     
---------------------------------------------------------------------------------------
Step    Variable                   AIC         SBC         SBIC        R2       Adj. R2 
---------------------------------------------------------------------------------------
 0      Base Model                -76.144     -50.964    -576.247    0.53048    0.51341 
 1      women_empowerment (+)    -180.455    -152.127    -678.110    0.74694    0.73614 
 2      corruption (+)           -222.457    -190.982    -718.039    0.80406    0.79445 
 3      polarization (+)         -221.737    -187.115    -717.119    0.80552    0.79471 
---------------------------------------------------------------------------------------

Final Model Output 
------------------

                         Model Summary                           
----------------------------------------------------------------
R                       0.898       RMSE                  0.119 
R-Squared               0.806       MSE                   0.014 
Adj. R-Squared          0.795       Coef. Var            29.883 
Pred R-Squared          0.779       AIC                -221.737 
MAE                     0.090       SBC                -187.115 
----------------------------------------------------------------
 RMSE: Root Mean Square Error 
 MSE: Mean Square Error 
 MAE: Mean Absolute Error 
 AIC: Akaike Information Criteria 
 SBC: Schwarz Bayesian Criteria 

                               ANOVA                                 
--------------------------------------------------------------------
               Sum of                                               
              Squares         DF    Mean Square      F         Sig. 
--------------------------------------------------------------------
Regression     10.111          9          1.123    74.552    0.0000 
Residual        2.441        162          0.015                     
Total          12.553        171                                    
--------------------------------------------------------------------

                                               Parameter Estimates                                                
-----------------------------------------------------------------------------------------------------------------
                               model      Beta    Std. Error    Std. Beta      t        Sig      lower     upper 
-----------------------------------------------------------------------------------------------------------------
                         (Intercept)     0.126         0.093                  1.351    0.179    -0.058     0.310 
                          log_wealth    -0.001         0.014       -0.006    -0.103    0.918    -0.029     0.026 
                 regionLatin America     0.062         0.034        0.081     1.837    0.068    -0.005     0.129 
                          regionMENA    -0.005         0.043       -0.006    -0.115    0.908    -0.091     0.081 
            regionSub-Saharan Africa    -0.011         0.035       -0.019    -0.320    0.749    -0.080     0.058 
regionWestern Europe &amp; North America     0.109         0.039        0.140     2.773    0.006     0.031     0.187 
                regionAsia &amp; Pacific    -0.029         0.036       -0.039    -0.806    0.422    -0.100     0.042 
                   women_empowerment     0.641         0.073        0.471     8.833    0.000     0.498     0.784 
                          corruption    -0.345         0.055       -0.391    -6.258    0.000    -0.453    -0.236 
                        polarization    -0.009         0.008       -0.045    -1.100    0.273    -0.026     0.007 
-----------------------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>The mandatory inclusion of wealth and regional indicators alters the selection process, demonstrating how theoretical considerations should guide rather than merely supplement statistical procedures. In this case, the theory guided approach essentially brought us back to the full model, but in other contexts you may find that the model is more parsimonious while still retaining theoretically important variables.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Your Turn!!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Apply model selection using AIC as the evaluation criterion for the democracy data by using the <code><a href="https://olsrr.rsquaredacademy.com/reference/ols_step_both_aic.html">ols_step_both_aic()</a></code> function from the <code>olsrr</code> package.</p>
<ol type="1">
<li>Perform bidirectional stepwise selection using AIC</li>
<li>Compare the selected variables to those chosen by adjusted R-squared</li>
<li>Calculate and compare AIC values for both the full model and your selected model</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Bidirectional selection using AIC</span></span>
<span><span class="va">aic_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://olsrr.rsquaredacademy.com/reference/ols_step_both_aic.html">ols_step_both_aic</a></span><span class="op">(</span><span class="va">full_model</span><span class="op">)</span></span>
<span><span class="va">aic_model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                                    Stepwise Summary                                     
---------------------------------------------------------------------------------------
Step    Variable                   AIC         SBC         SBIC        R2       Adj. R2 
---------------------------------------------------------------------------------------
 0      Base Model                 41.896      48.191    -449.065    0.00000    0.00000 
 1      women_empowerment (+)    -131.886    -122.444    -622.069    0.64012    0.63801 
 2      corruption (+)           -217.702    -205.112    -706.085    0.78402    0.78146 
 3      region (+)               -224.442    -196.115    -720.133    0.80405    0.79568 
---------------------------------------------------------------------------------------

Final Model Output 
------------------

                         Model Summary                           
----------------------------------------------------------------
R                       0.897       RMSE                  0.120 
R-Squared               0.804       MSE                   0.014 
Adj. R-Squared          0.796       Coef. Var            29.812 
Pred R-Squared          0.784       AIC                -224.442 
MAE                     0.090       SBC                -196.115 
----------------------------------------------------------------
 RMSE: Root Mean Square Error 
 MSE: Mean Square Error 
 MAE: Mean Absolute Error 
 AIC: Akaike Information Criteria 
 SBC: Schwarz Bayesian Criteria 

                               ANOVA                                 
--------------------------------------------------------------------
               Sum of                                               
              Squares         DF    Mean Square      F         Sig. 
--------------------------------------------------------------------
Regression     10.093          7          1.442    96.133    0.0000 
Residual        2.460        164          0.015                     
Total          12.553        171                                    
--------------------------------------------------------------------

                                               Parameter Estimates                                                
-----------------------------------------------------------------------------------------------------------------
                               model      Beta    Std. Error    Std. Beta      t        Sig      lower     upper 
-----------------------------------------------------------------------------------------------------------------
                         (Intercept)     0.135         0.075                  1.798    0.074    -0.013     0.283 
                   women_empowerment     0.640         0.072        0.470     8.874    0.000     0.498     0.783 
                          corruption    -0.359         0.045       -0.407    -8.050    0.000    -0.447    -0.271 
                 regionLatin America     0.064         0.033        0.083     1.900    0.059    -0.003     0.130 
                          regionMENA    -0.007         0.043       -0.008    -0.163    0.871    -0.092     0.078 
            regionSub-Saharan Africa    -0.013         0.030       -0.021    -0.430    0.668    -0.072     0.046 
regionWestern Europe &amp; North America     0.110         0.039        0.141     2.822    0.005     0.033     0.186 
                regionAsia &amp; Pacific    -0.031         0.035       -0.041    -0.884    0.378    -0.099     0.038 
-----------------------------------------------------------------------------------------------------------------</code></pre>
</div>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Compare AIC values</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Full Model AIC:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/AIC.html">AIC</a></span><span class="op">(</span><span class="va">full_model</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Full Model AIC: -221.74 </code></pre>
</div>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Selected Model AIC:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/AIC.html">AIC</a></span><span class="op">(</span><span class="va">aic_model</span><span class="op">$</span><span class="va">model</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Selected Model AIC: -224.44 </code></pre>
</div>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Compare which variables were selected</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"\nVariables in Adjusted R-squared model:"</span>, </span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">both_model</span><span class="op">$</span><span class="va">model</span><span class="op">)</span><span class="op">)</span><span class="op">[</span><span class="op">-</span><span class="fl">1</span><span class="op">]</span>, collapse <span class="op">=</span> <span class="st">", "</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Variables in Adjusted R-squared model: women_empowerment, corruption, regionLatin America, regionMENA, regionSub-Saharan Africa, regionWestern Europe &amp; North America, regionAsia &amp; Pacific, polarization </code></pre>
</div>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Variables in AIC model:"</span>, </span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">aic_model</span><span class="op">$</span><span class="va">model</span><span class="op">)</span><span class="op">)</span><span class="op">[</span><span class="op">-</span><span class="fl">1</span><span class="op">]</span>, collapse <span class="op">=</span> <span class="st">", "</span><span class="op">)</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Variables in AIC model: women_empowerment, corruption, regionLatin America, regionMENA, regionSub-Saharan Africa, regionWestern Europe &amp; North America, regionAsia &amp; Pacific </code></pre>
</div>
</div>
</div>
</div>
</div>
</section><section id="additional-methodological-considerations" class="level2"><h2 class="anchored" data-anchor-id="additional-methodological-considerations">Additional Methodological Considerations</h2>
<section id="multicollinearity" class="level3"><h3 class="anchored" data-anchor-id="multicollinearity">Multicollinearity</h3>
<p><strong>Multicollinearity</strong> occurs when predictor variables exhibit substantial correlations with one another. This condition creates several analytical problems including unstable coefficient estimates, inflated standard errors that reduce the power to detect significant relationships, and interpretation difficulties when attempting to isolate individual variable effects.</p>
<p><strong>Variance Inflation Factors (VIF)</strong> provide a diagnostic tool for assessing multicollinearity severity:</p>
<p>We can use the <code><a href="https://olsrr.rsquaredacademy.com/reference/ols_coll_diag.html">ols_vif_tol()</a></code> function from the <code>olsrr</code> package to calculate VIF values for the full model:</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://olsrr.rsquaredacademy.com/reference/ols_coll_diag.html">ols_vif_tol</a></span><span class="op">(</span><span class="va">full_model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                             Variables Tolerance      VIF
1                           log_wealth 0.3106153 3.219416
2                         polarization 0.7322931 1.365573
3                    women_empowerment 0.4230084 2.364019
4                           corruption 0.3080812 3.245898
5                  regionLatin America 0.6160077 1.623356
6                           regionMENA 0.4755160 2.102979
7             regionSub-Saharan Africa 0.3557731 2.810780
8 regionWestern Europe &amp; North America 0.4714850 2.120958
9                 regionAsia &amp; Pacific 0.5080389 1.968353</code></pre>
</div>
</div>
<p>Conventional guidelines suggest that VIF values exceeding 5-10 indicate problematic multicollinearity requiring remedial action. Here we do not see any variables exceeding that threshold so we should feel comfortable ruling out multicollinearity as a major concern in this model.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Another common package for calculating VIF is <code>car</code>, which provides the <code>vif()</code> function. You can use it by simply loading <code>car</code> (after you have installed it of course!) and running <code>vif(full_model)</code>.</p>
</div>
</div>
<p>Examination of correlations among continuous predictors provides additional insight into potential multicollinearity issues:</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Correlation matrix for numeric predictors</span></span>
<span><span class="va">model_data</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">log_wealth</span>, <span class="va">polarization</span>, <span class="va">women_empowerment</span>, <span class="va">corruption</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  log_wealth polarization women_empowerment corruption
log_wealth             1.000       -0.381             0.340     -0.674
polarization          -0.381        1.000            -0.312      0.500
women_empowerment      0.340       -0.312             1.000     -0.594
corruption            -0.674        0.500            -0.594      1.000</code></pre>
</div>
</div>
<p>Here we would be looking for correlations exceeding 0.7 or 0.8, which would indicate potential multicollinearity concerns. In this case, we do not see any such high correlations, again giving us confidence to proceed with the analysis.</p>
</section><section id="sample-size-requirements" class="level3"><h3 class="anchored" data-anchor-id="sample-size-requirements">Sample Size Requirements</h3>
<p>Adequate sample sizes ensure reliable parameter estimation in multiple regression models. The conventional guideline recommends minimum ratios of 10-15 observations per predictor variable. The current analysis includes 172 observations and 9 predictors, yielding a ratio of 19.1:1, which meets standard adequacy thresholds.</p>
</section><section id="model-validation" class="level3"><h3 class="anchored" data-anchor-id="model-validation">Model Validation</h3>
<p>Selected models require validation to assess their reliability and generalizability. <strong>Residual analysis</strong> examines whether regression assumptions hold in the fitted model. <strong>Cross-validation</strong> techniques test model performance on independent data subsets. <strong>Out-of-sample prediction</strong> provides the strongest test of model generalizability when feasible. <strong>Substantive interpretation</strong> ensures that statistical results align with theoretical expectations and domain knowledge. We will discuss some of these issues in greater detail in a subsequent module on regression diagnostics.</p>
</section></section><section id="summary" class="level2"><h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>Model selection involves balancing competing objectives of explanatory power and parsimony. Multiple evaluation criteria exist, including adjusted R-squared, AIC, and p-values, each with distinct properties that can lead to different optimal models. Automated stepwise procedures provide systematic approaches to variable selection, though they should supplement rather than replace theoretical reasoning.</p>
<p>Domain knowledge plays a crucial role in model specification, often requiring the retention of theoretically important variables regardless of their statistical performance in particular samples. Additional methodological considerations include multicollinearity assessment, sample size adequacy, and model validation procedures.</p>
<p>The ultimate goal of model selection extends beyond maximizing statistical criteria to developing models that are simultaneously statistically sound and substantively meaningful. This dual objective requires integrating statistical techniques with theoretical understanding and domain expertise throughout the modeling process.</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ds4all\.rocks");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2025, <a href="https://emmanuel.teitelbaum.com">Emmanuel Teitelbaum</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/eteitelbaum/dats1001-summer/edit/main/modules/module-4.5.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/eteitelbaum/dats1001-summer/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This page is built with <a href="https://quarto.org/">Quarto</a>. 👷🛠️</p>
</div>
  </div>
</footer>


</body></html>