---
title: "Syllabus"
---

## Course information

| Course: DATS 1001-Data Science for All
| Lecture: WF 11:10-12:25
| Classroom: [Duques Hall](https://g.co/kgs/81oCUV4) Rm. 152
|
| Instructor: Prof. Emmanuel Teitelbaum
| Email: [ejt\@gwu.edu](mailto:ejt@gwu.edu)
| Office Hours: Mondays 9-11 a.m. and by appointment.
| Location: Online or in [Monroe Hall](https://g.co/kgs/yuSsRto), Rm. 411, Sign up [here](https://calendly.com/emmanuel-teitelbaum)
|
| Teaching Assistant: Gourab Mukherjee
| Email: [gourab.mukherjee\@email.gwu.edu](mailto:gourab.mukherjee@email.gwu.edu)
| Office Hours: Fridays, 3-5 p.m.
| Location: Online, follow [this link](https://gwu-edu.zoom.us/my/gourabmukherjee)
|
| Teaching Assistant: Sai Srinivas Lakkoju
| Email: [saisrinivas.lakkoju\@email.gwu.edu](mailto:saisrinivas.lakkoju@email.gwu.edu)
| Office Hours: Thursdays, 1-3 p.m. 
| Location: Online, follow [this link](https://gwu-edu.zoom.us/my/saisrinivaslakkoju)
|
| Credit Hours: 3.0.

## Learning Objectives

1. **Develop Proficiency in R Programming**: Students will learn the fundamentals of R programming, including basic syntax, data manipulation, and the use of R packages, enabling them to write and execute R scripts effectively.

2. **Master Data Visualization Techniques**: Students will gain a deep understanding of the grammar of graphics and best practices in data visualization, allowing them to create clear, accurate, and impactful visual representations of data.

3. **Apply Data Wrangling Techniques**: Students will learn to organize, clean, and transform datasets into tidy formats using R, preparing them for analysis by applying grouping, summarizing, and joining operations.

4. **Understand and Implement Statistical Models**: Students will learn the principles of statistical modeling, including linear, multiple, and logistic regression, and will apply these models to real-world data to make predictions and informed decisions.

5. **Conduct Hypothesis Testing and Interpret Results**: Students will learn the concepts of sampling, uncertainty, and hypothesis testing, enabling them to design research studies, test hypotheses, and draw valid conclusions from data.

## Readings

Students will read approximately 20 pages per week of academic material during the semester.

All academic readings will be linked to the course website. There are no textbooks that need to be purchased for this course. 

## Assignments

1.  Quizzes (20%)
2.  Coding assignments (40%)
3.  Final project (40% of final grade)
    a. Proposal (5%)
    b. Data Preparation (5%)
    c. Lightning Talk (10%)
    d. Report (20%)

### Quizzes

Students will complete approximately ten graded quizzes. These exercises will be oriented towards strengthening the student's ability to manipulate, visualize and communicate data with R and Quarto. I will drop your lowest two quiz scores so you do not have to worry about making up missed quizzes. **Please do not email me about missed quizzes.**

### Coding Assignments

Students will complete four weekly coding assignments. These assignments are designed to provide students with the opportunity to apply their newly-acquired skills to real world data and to develop their ability to write and execute R scripts. 

### Final Project

Each student will complete a final project that will be developed throughout the semester. Students will work in groups to complete the project. The ultimate objective of this project is to design and execute an original data analysis. Details on the project will be provided in class over the course of the semester.

## Course Grading

The grading scale below maps your final point or percentage total to your final letter grade for the course.

| Range  | Letter Grade |
|:------:|:------------:|
| 94-100 |      A       |
| 90-93  |      A-      |
| 87-89  |      B+      |
| 84-86  |      B       |
| 80-83  |      B-      |
| 77-79  |      C+      |
| 74-76  |      C       |
| 70-73  |      C-      |
| 67-69  |      D+      |
| 64-66  |      D       |
| 60-63  |      D-      |
|  \<59  |      F       |

## Late Work

Late assignments will incur a penalty of 1 percentage point per day. Late work **will not be accepted more than 7 days past the deadline.** Please also note that there will be **no makeups** for missed quizzes.

Students with exceptional circumstances may receive accommodations for late work under exceptional circumstances, and in consultation with the students' academic advisor, when a verified medical excuse written by a qualified medical professional is provided.

Accommodations are automatically approved for university-approved absences such as sporting events, religious holidays, etc. but these should be provided to the instructor by the end of the second week of the semester.

No exceptions will be made to the late work policy.

## Course Communication 

### Discord  

The best way to ask questions about concepts and coding issues or anything related to the course material (including assignment requirements and due dates) is via a public post on the course *Discord server*.  This is going to be our main communication channel for a few reasons:

1) You can insert code snippets and images directly into your questions, which will make it easier for us to understand your problem and provide you with a solution (whereas with email you cannot); 

2) Other students can see your question and the answer, which will everyone to learn from the discussion. You may think you are the only one with a question, but chances are that if you are thinking something so are others in the course; 

3) Discord helps to establish a sense of community among students, and we want this course to feel like a modern, supportive and inclusive data science community. 

The TAs and I will check the Discord at least once a day and will respond to your questions as soon as possible. 

Please **do not send emails** questions about the course material. Please also **do not send direct messages (DMs)** or friend requests on Discord. We will only respond to public messages. Although it may be very kind to send them, friend requests will be ignored due to the need to maintain professional boundaries between students and instructors.

The link to the Discord server will be distributed at the start of the semester via Blackboard. Please make sure to join the server as soon as possible as the link will expire after a few days.

### Office hours

If you have asked your question on Discord and could not get an answer, you can come to office hours. You can also come to office hours if you have a personal matter that you would like to discuss. For content-related questions, the TAs will be your first point of contact. If they cannot answer your question, they will refer you to me, at which point you can sign up for one of my office hour slots via Calendly.

To make the meeting more effective, you can:

-   Gather materials (assignments, notes, etc.) ready in advance
-   Be ready to take notes during office hours
-   Ask follow up questions if you need clarification
-   Confirm any action plan at the close of the meeting
-   Following through on any action plan

### Email

Emails should be kept to a minimum in this course. But if you have tried the Discord and office hours and still have a question, you can email me. Please make sure to include "DATS 1001" in the subject line of your email. I will do my best to respond to your email within 24 hours.

## Netiquette

Behind every name there is a person.

To ensure safe and meaningful learning experiences for everyone, we all agree to:

-   Remain professional, respectful, and courteous at all times on all platforms.
-   Keep in mind this is a college class. Something that would be inappropriate in an in-person classroom is also inappropriate in an online classroom.
-   When upset, we'll wait a day or two prior to posting. Messages posted or emailed in anger are often regretted later.
-   Ask one another for clarification if we find a communication offensive or difficult to understand.
-   Avoid sweeping generalizations. Back up our stated opinions with facts and reliable sources.
-   Understand that we may disagree and that exposure to other people's opinions is part of the learning experience.
-   Just as we would like our privacy respected, we will respect the privacy of other course participants and what they share.

I (the instructor) reserve the right to delete any post or communication in our course that is deemed inappropriate without prior notification to the student. This includes anything containing language that is offensive, rude, profane, racist, or hateful. Items that are seriously off-topic or serve no purpose other than to vent frustration will also be removed.

Using outside communication apps

I am aware that you and your peers might communicate using tools outside of GW's Blackboard, my course website, our course Discord channel, or email systems. Rules of netiquette and appropriate communication extend to these tools as well as to Blackboard. If you see any tool being used inappropriately (i.e., any communication containing language that is offensive, rude, profane, racist, or hateful; uses that promote cheating of any kind), contact me as soon as possible to speak privately about it.

(Adapted from [Lake Superior Connect, Creative Commons Attribution 3.0](https://creativecommons.org/licenses/by/3.0/))

## Policy on AI Tools

### Overview

The use of Large Language Models (LLMs) can be a valuable tool for students in this course, but it is important to use it ethically and appropriately. By following the guidelines and expectations outlined in this syllabus policy, students can maximize the benefits of using LLMs while also demonstrating their own critical thinking, research, and programming skills.

As part of this course, students will have the option to use ChatGPT and other LLMs to assist in the writing of their R scripts for specific course assignments. Such tools can provide students with a starting point for their code but often the code is incomplete or error-prone. It is important to recognize that LLMs are a tool and not a substitute for critical thinking, research, or programming skills. Therefore, this syllabus policy outlines the guidelines and expectations for using LLMs in this course.

### Guidelines

It is also important to note that some uses of LLMs are more appropriate than others. For example, it is acceptable to use LLMs to generate boilerplate code or to help with syntax, but it is not acceptable to use an LLM to complete entire assignments or assessments. Students should use LLMs as a starting point and then modify and expand on the generated code to demonstrate their own understanding and skills. 

One way to think of LLMs is as a tutor or classmate. What would it be appropriate to ask a tutor or classmate for help with? What would you not be permitted ask a tutor or classmate for help with?

## Prerequisites

### Academic

There are no academic prerequisites for this course.

### Technological

#### Configuration and software

To fully participate in our course, you will need regular access to broadband Internet access as well as other technology components. Please consult [GW Online's Technical Requirements and Support](https://online.gwu.edu/technical-requirements-and-support) for details on recommended configurations and software available to you. You will need to use the following tools and platforms:

-   [Posit Cloud](https://posit.cloud): a cloud-based computing platform that allows you to run R code and render Quarto documents in the cloud.You will need to purchase a student subscription ($5/month) to access the class workspace.
-   RStudio: an IDE for generating data visualizations using the programming language, R.
-   Quarto: a document generation tool that allows you to create documents that combine code, data, and text.
-   Discord: a real-time chat application.

#### Skills

For our course, you should be able to:

-   Access and use [GW's Blackboard system](https://blackboard.gwu.edu).
-   Use your GW email for university-related communications [per university policy](https://registrar.gwu.edu/university-policies#email).
-   Use productivity software (e.g., Office 365, Google Suite) to collaborate with peers and submit assignments.
-   Use web conferencing tools (e.g., Zoom, Webex) to collaborate with peers and me.
-   Use a mobile device and/or computer to upload documents, images, and recordings.
-   Seek technology help and tools by contacting [GW Information Technology](https://online.gwu.edu/student-support) \| (202)-994-4948 \| [ithelp\@gwu.edu](mailto:ithelp@gwu.edu).

If you need assistance with technology tools we'll use in this course, please visit the **Technology Support** link in the left navigation menu in our course on Blackboard.

## Course Credit Hour Policy

Summer courses are more than twice as intensive as those held during the academic year. Over 6 weeks, students will spend approximately 18.75 hours per week doing independent learning, including, but not limited to, readings, quizzes, assignments and a final project. This amounts to 36 hours of direct-instruction and 76.5 hours independent coursework.

### How this applies to you

Use the credit hour policy to plan and manage your workload and time spent on this course. Please contact me if you are having difficulty managing your workload, and we can discuss strategies to help you succeed in the course.

## Demonstrating Academic Integrity

All of us in the course will comply with [the GW Code of Academic Integrity](https://studentconduct.gwu.edu/). It states that "we, the Students, Faculty, Librarians, Staff, and Administration of The George Washington University, believing academic integrity to be central to the mission of the University, commit ourselves to promoting high standards for the integrity of academic work. Commitment to academic integrity upholds educational equity, development, and dissemination of meaningful knowledge, and mutual respect that our community values and nurtures. The George Washington University Code of Academic Integrity is established to further this commitment."

Academic dishonesty is defined as cheating of any kind, including misrepresenting one's own work, taking credit for the work of others without crediting them and without appropriate authorization, and the fabrication of information. For details and complete code, see the [Code of Academic Integrity.](http://studentconduct.gwu.edu/code-academic-integrity)Common examples of academic dishonesty include cheating, fabrication, plagiarism, falsification, forgery of University academic documents, and facilitating academic dishonesty by others. Learn more about avoiding these:

-   [GW guidance for students on academic integrity](https://studentconduct.gwu.edu/guidance-students).

-   [Plagiarism: What is it and how to avoid it](https://libguides.gwu.edu/plagiarism) from GW Libraries.

-   Maintaining academic honesty can be a challenging skill to learn. If you have questions about maintaining our course standards, please talk with me early on.

## Aiming For Success

I care about your learning and also about this subject matter, and I am here to help you have a meaningful learning experience. I expect you to take ownership of your learning: you can get more out of the course by thoughtfully participating in discussions, actively taking notes on readings and lectures, and giving your best effort overall. I will hold you to the highest standards for academic honesty and integrity in your work. I will also encourage you to collaborate and learn from your peers through thoughtful and respectful discussion. It is recommended you log in daily order to keep up with course requirements. I must highlight that communication is vital, so I hope you feel comfortable reaching out to me if you are struggling or have concerns or need [accommodations beyond accessibility](#_heading=h.41mghml). We can determine strategies to set you up for success. Finally, I look forward to collaborating with you in this course to create a meaningful experience for everyone.

## Policies

To make this a meaningful learning experience for everyone, please read and understand the following policies. [All GW policies can be found on the GW Office of Ethics, Compliance, and Privacy site](https://compliance.gwu.edu/policies). All GW community members are responsible for adhering to and activating in accordance with all university policies. Please contact me if you have any questions.

## Accessibility and Accommodations

### GW's Disability Support Services

If you are a student with a disability, or think you may have a disability, you can let me know, and/or you can talk to [GW's Office of Disability Support Services (DSS)](https://disabilitysupport.gwu.edu/). DSS works with both students with disabilities and instructors to identify reasonable accommodations. Contact the DSS office at (202) 994-8250, by email on dss\@gwu.edu, or in-person in Rome Hall Suite 102 to establish eligibility and to coordinate reasonable accommodations. If you have already been approved for accommodations, please send me your accommodation letter and meet with me so we can develop an implementation plan together.

How are course technology tools accessible to everyone? To find out, access **Technology Support Technology Tools Policies** in the Blackboard course menu.

### Accommodations Beyond Disability

Everyone has different needs for learning. If you don't have a documented disability but feel that you would benefit from learning support for other reasons, please don't hesitate to talk to me. If you have substantial non-academic obligations or other concerns (e.g., [food insecurity](https://studentlife.gwu.edu/store), work, childcare, athletic commitments, language barriers, financial issues, technology access, commuting, etc.) that make learning difficult, please contact me. I'll keep this information confidential, and together, we can brainstorm ways to meet your needs.

### Other Needs

Any student who has difficulty affording groceries or accessing sufficient food to eat every day, or who lacks a safe and stable place to live, and believes this may affect their performance in the course, is urged to contact [GW's Office of Student Financial Assistance](https://financialaid.gwu.edu/emergency-funding) for support. Furthermore, please notify me if you are comfortable doing so. Some other resources to support you are found under the course menu item **Student Resources** and include support for academic achievement and personal well-being. *(Adapted from Goldrick-Rab, 2017)*

## Counseling and Psychological Services

GW's Health Center offers [counseling and psychological services](http://counselingcenter.gwu.edu) to GW students. ***Please note that staff is licensed to offer short term therapy to students in Washington, DC, Maryland, and Virginia. If you are living outside these regions, the office may be able to refer you elsewhere.*** Assistance and referrals 24 hours a day, 365 days a year and can be reached on (202) 994-5300.

The Center provides assistance and referral to address students' personal, social, career, and study skills problems. Services for students include: crisis and emergency mental health consultations, confidential assessment, counseling services (individual and small group), and referrals.

[Virtual Workshops](https://healthcenter.gwu.edu/sites/g/files/zaxdzs1216/f/image/Virtual%20Workshop%20Flyer.pdf) are open to any student regardless of geographic location. These can be exceptionally valuable and help you build essential skills and cope with common ongoing mental health concerns. Please contact the [GW Health Center](https://healthcenter.gwu.edu) on (202) 994-5300 for more information.

## Religious Observances

As members of the GW community, you have the right to observe religious holidays. University policy requires that students notify their instructors during the first week of the semester if they plan to be absent from class on days of religious observance. For further details, please consult [the university policy on religious holiday observance](http://registrar.gwu.edu/university-policies#holidays).

## Key Dates

Please defer to the due dates listed on the course website. You can also view due dates in the gradebook and under each individual course assignment item in Blackboard Ultra.

## Incomplete Grades

### Undergraduate students

Incomplete grades may be given to undergraduate students only if for reasons beyond the student's control (such as medical or family emergency) they are unable to complete the final work of the course. Faculty should not assign an Incomplete grade if not asked by the student.

[A contract](https://advising.columbian.gwu.edu/sites/g/files/zaxdzs1876/f/downloads/Form%20-%20Incomplete%20Contract_1.pdf) must be signed by the instructor and the student and filed in the department office. A copy should be submitted to the Academic Advising office in Phillips 107. A student has up to a calendar year to finish the coursework for the class, and when completed a grade change form must be submitted to the Academic Advising office to update the grade.

For further policy and contract information for undergraduate students, please consult with your advisor and also visit the website for [Columbian College of Arts and Sciences Academic Advising.](https://columbian.gwu.edu/sites/g/files/zaxdzs4901/files/2022-06/ccas_incomplete_contract_21.pdf)

### Graduate students

Incomplete grades may be given to graduate students only if for reasons beyond the student's control (such as medical or family emergency) they are unable to complete the final work of the course. Faculty should not assign an Incomplete grade if not asked by the student.

For further information, please consult with your advisor and complete a [CCAS graduate student incomplete grade form.](https://columbian.gwu.edu/sites/g/files/zaxdzs1971/f/downloads/DGS/Incomplete%20Contract.pdf)
