---
title: "Course Schedule"
tbl-colwidths: [5,15,30,5,5,5,5,15]
editor: visual
---

```{r setup, include = FALSE}
library(lubridate)

sun <- as_date("2025-05-18")
mon <- sun+days(1)
tues <- sun+days(2)
wed <- sun+days(3)
thur <- sun+days(4)
fri <- sun+days(5)
sat <- sun+days(6)

advdate <- function(day, week) {
  date <- (day + weeks(week))
  # Extract day of the week and calendar date
  dow <- wday(date, label = TRUE, abbr = TRUE)  # Get day of week
  dm <- paste(month(date, label = TRUE)," ",day(date))
  return(paste0(dow, ", ", dm))
}
```

This page displays an outline of the topics, content, and assignments
for the semester. Links, to slides, assignments and course resources
will go live as the semester progresses.

::: column-screen-inset-right
| Week | Date | Topic | Reading | Video | Module | Assignment | Due Date |
|:-------:|---------|---------|:-------:|:-------:|:-------:|:-------:|:-------:|
| 1 | `r advdate(mon,0)` | Getting started | [ðŸ“–](https://rstudio-education.github.io/hopr/starting.html "hopwr, Appendix A and B") [ðŸ“–](https://quarto.org/docs/get-started/hello/rstudio.html "Hello, Quarto") | [ðŸ“º](https://youtu.be/eimM6pNkYjE "R & RStudio") [ðŸ“º](https://youtu.be/6QN9ZYURDFg "Getting Started with Quarto") | [ðŸ“’](/modules/module-1.1.qmd "Getting Started") |  |  |
|  | `r advdate(tues,0)` | Meet ouR tech stack | [ðŸ“–](https://www.markdownguide.org/getting-started/ "Markdown Guide") | [ðŸ“º](https://youtu.be/bTVIMt3XllM?si=krDEL4lvyT-T5DZc "Markdown Crash Course") | [ðŸ“’](modules/module-1.2.qmd "Meet ouR Tech Stack") |  |  |
|  | `r advdate(wed,0)` | R Coding basics | [ðŸ“–](https://rstudio-education.github.io/hopr/basics.html "hopwr, ch. 2") | [ðŸ“º](https://www.youtube.com/watch?v=hvFBDmT4bdY "Using Functions and Objects in R") [ðŸ“º](https://youtu.be/9f2g7RN5N0I?si=WMsaGlhFC7Fx-ZNy "Explore the Data Frame") | [ðŸ“’](modules/module-1.3.qmd "R Coding Basics") | ðŸ“˜ | `r advdate(wed,0)` |
|  | `r advdate(thur,0)` | Intro to the Tidyverse | [ðŸ“–](https://r4ds.hadley.nz/intro "rd4s, intro") | [ðŸ“º](https://youtu.be/izFssYRsLZs?si=b6Oy4atpRrkfEKzB "Hadley Wickham on code maintenance") | [ðŸ“’](modules/module-1.4.qmd "Reading Data into R") |  |  |
|  | `r advdate(fri,0)` | Grammar of graphics | [ðŸ“–](https://r4ds.hadley.nz/data-import "r4ds, chap. 7") [ðŸ“–](https://r4ds.hadley.nz/data-visualize.html "r4ds, 2") | [ðŸ“º](https://youtu.be/QG1oDJPoIio "Make a bar chart") [ðŸ“º](https://youtu.be/-1YhCql-gMo "Make a histogram") | [ðŸ“’](modules/module-1.5.qmd "Grammar of Graphics") |  |  |
|  | `r advdate(sat,0)` | Advanced data viz techniques | [ðŸ“–](https://r4ds.hadley.nz/layers "r4ds, 9.1-9.4") | [ðŸ“º](https://youtu.be/PnmQ2MFQpIc "Make a line chart") [ðŸ“º](https://youtu.be/FiosjUVyfLM "Make a scatterplot") | [ðŸ“’](modules/module-1.6.qmd "Advanced Data Viz Techniques") | ðŸ“˜ [ðŸ§®](assignments/coding-assignment-1.qmd "Coding assignment 1") | `r advdate(sun,1)` |
| 2 | `r advdate(mon,1)` | What is tidy data? | [ðŸ“–](https://r4ds.hadley.nz/data-tidy#sec-tidy-data "r4ds, chap. 5.2") | [ðŸ“º](https://www.youtube.com/watch?v=oQuupzfX9OQ "Principles of Tidy Data") | [ðŸ“’](modules/module-2.1.qmd "What is Tidy Data?") |  |  |
|  | `r advdate(tues,1)` | Transforming data | [ðŸ“–](https://r4ds.hadley.nz/data-transform "rd4s, chap. 3.1-3.4") | [ðŸ“º](https://youtu.be/ScQD47eJeAE?si=Rc6epCTKhQVtkCjS "Transforming data w/ dplyr verbs") | [ðŸ“’](modules/module-2.2.qmd "Transforming Data") |  |  |
|  | `r advdate(wed,1)` | Summarizing data | [ðŸ“–](https://r4ds.hadley.nz/data-transform#groups "r4ds, chap. 3.5") | [ðŸ“º](https://youtu.be/mgBwVzMV-v8?si=4KP-qyDyssI92iFe "Grouping and summarizing data") | [ðŸ“’](modules/module-2.3.qmd "Summarizing Data") | ðŸ“˜ | `r advdate(wed,1)` |
|  | `r advdate(thur,1)` | Joining data frames | [ðŸ“–](https://r4ds.hadley.nz/joins.html "r4ds, chap. 19") | [ðŸ“º](https://youtu.be/wNF3ZPneHWw?si=TyiXrsAxgbdrztD4 "Merge data frames with left_join()") | [ðŸ“’](modules/module-2.4.qmd "Joining Data Frames") |  |  |
|  | `r advdate(fri,1)` | Tidying data | [ðŸ“–](https://r4ds.hadley.nz/data-tidy "r4ds, chap. 5.3-5.5") |  | [ðŸ“’](modules/module-2.5.qmd "Tidying Data") |  |  |
|  | `r advdate(sat,1)` | Cleaning data | [ðŸ“–](https://link.springer.com/article/10.1057/palgrave.ap.5500151 "Norris") | [ðŸ“º](https://youtu.be/ZwJsSjJRuMU "Reading Data into R with read_csv()") [ðŸ“º](https://youtu.be/u4AXi8A1Bqo?si=OVnjerTuxm6bYIKb "Reshaping Data in R") [ðŸ“º](https://youtu.be/xa0tYCfHHTI?si=1YII-L90IY05UZ70 "Cleaning Data in R") | [ðŸ“’](modules/module-2.6.qmd "Cleaning Data") | ðŸ“˜ [ðŸ§®](assignments/coding-assignment-2.qmd "Coding assingment 2") | `r advdate(sun,2)` |
| 3 | `r advdate(mon,2)` | Categorical data | [ðŸ“–](https://openintro-ims.netlify.app/explore-categorical "IMS, chap. 4") | [ðŸ“º](https://youtu.be/7NhNeADL8fA?si=InH8FFc1BIVT0ktM "Exploring Categorical Data") | [ðŸ“’](modules/module-3.1.qmd "Categorical Data") |  |  |
|  | `r advdate(tues,2)` | Continuous data | [ðŸ“–](https://openintro-ims.netlify.app/explore-numerical "IMS, chap. 5.1 - 5.3") | [ðŸ“º](https://youtu.be/Xm0PPtci3JE?si=MocqDt05YqllA9k5 "Exploring Numerical Data") | [ðŸ“’](modules/module-3.2.qmd "Continuous Data") |  |  |
|  | `r advdate(wed,2)` | Describing Distributions | [ðŸ“–](https://openintro-ims.netlify.app/explore-numerical#sec-variance-sd "IMS, chap. 5.4 - 5.5") |  | [ðŸ“’](modules/module-3.3.qmd "Describing Distributions") | ðŸ“˜ | `r advdate(wed,2)` |
|  | `r advdate(thur,2)` | Sampling and uncertainty | [ðŸ“–](https://openintro-ims.netlify.app/foundations-bootstrapping "IMS, chap. 12") | [ðŸ“º](https://www.youtube.com/watch?v=5q2ac412hv4 "The Right and Wrong Way to Interpret a CI") [ðŸ“º](https://youtu.be/Xz0x-8-cgaQ?si=v_YCi-dU5YBdcb99 "Bootstrapping Main Ideas") | [ðŸ“’](modules/module-3.4.qmd "Sampling and uncertainty") |  |  |
|  | `r advdate(fri,2)` | Single proportion tests | [ðŸ“–](https://openintro-ims.netlify.app/inference-one-prop "IMS, chap. 16") |  | [ðŸ“’](modules/module-3.5.qmd "Single Proportion Tests") |  |  |
|  | `r advdate(sat,2)` | Differences between two groups | [ðŸ“–](https://openintro-ims.netlify.app/foundations-randomization "IMS, chap. 11") | [ðŸ“º](https://www.youtube.com/watch?v=2pHhjx9hyM4 "Using Randomization to Analyze Gender Discrimination") | [ðŸ“’](modules/module-3.6.qmd "Differences Between Two Groups") | ðŸ“˜ [ðŸ§®](assignments/coding-assignment-3.qmd "Coding assingment 3") | `r advdate(sun,3)` |
| 4 | `r advdate(mon,3)` | The language of models |  |  | ðŸ“’ |  |  |
|  | `r advdate(tues,3)` | Interpreting linear models | [ðŸ“–](https://openintro-ims.netlify.app/model-slr "IMS, chap. 7") | [ðŸ“º](https://youtu.be/dLc-lfEEYss?si=-Zelb-HBAP-MPvnF) | ðŸ“’ |  |  |
|  | `r advdate(wed,3)` | Estimation and line fitting |  |  | ðŸ“’ | ðŸ“˜ | `r advdate(wed,3)` |
|  | `r advdate(thur,3)` | Multiple regression | [ðŸ“–](https://openintro-ims.netlify.app/model-mlr "IMS, chap. 8") | [ðŸ“º](https://youtu.be/jXg0vU0y1ak?si=rhQ9uWhuhVqnI-Ox) | ðŸ“’ |  |  |
|  | `r advdate(fri,3)` | Assumptions, EDA and diagnostics |  |  | ðŸ“’ |  |  |
|  | `r advdate(sat,3)` | Feature engineering |  |  | ðŸ“’ | ðŸ“˜ ðŸ§® | `r advdate(sun,4)` |
| 5 | `r advdate(mon,4)` | Why logistic regression? | [ðŸ“–](https://openintro-ims.netlify.app/model-logistic "IMS, chap. 9") | [ðŸ“º](https://youtu.be/xuTiAW0OR40?si=sUoIr5pzHwHEpazO) | ðŸ“’ |  |  |
|  | `r advdate(tues,4)` | The logistic regression model | ðŸ“– ðŸ“– | ðŸ“º | ðŸ“’ |  |  |
|  | `r advdate(wed,4)` | Interpreting results |  | ðŸ“º | ðŸ“’ | ðŸ“˜ | `r advdate(wed,4)` |
|  | `r advdate(thur,4)` | Prediction and overfitting |  |  | ðŸ“’ |  |  |
|  | `r advdate(fri,4)` | Model evaluation |  |  | ðŸ“’ |  |  |
|  | `r advdate(sat,4)` | Multiple predictors, interactions and diagnostics | ðŸ“– |  | ðŸ“’ | ðŸ“˜ ðŸ§® | `r advdate(sun,5)` |
| 6 | `r advdate(mon,5)` | Final Project |  |  | ðŸ“’ | [âœï¸](project/project-assignment-1.qmd "Project assignment 1") | `r advdate(mon,5)` |
|  | `r advdate(tues,5)` | Final Project |  |  | ðŸ“’ |  |  |
|  | `r advdate(wed,5)` | Final Project |  |  |  | [âœï¸](project/project-assignment-2.qmd "Project assignment 2") | `r advdate(wed,5)` |
|  | `r advdate(thur,5)` | Final Project |  |  |  |  |  |
|  | `r advdate(fri,5)` | Final project |  |  |  |  |  |
|  | `r advdate(sat,5)` | Final project |  |  |  | [âœï¸](project/project-assignment-3.qmd "Project assignment 3") | `r advdate(sat,5)` |
:::
