{
  "hash": "526bf1f1b7cdf7535d2714384768ff3f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Module 5.4\"\nsubtitle: \"Multiple Predictors and Interactions\"\nformat: \n  html:\n    code-link: true\nhighlight-style: atom-one\nexecute: \n  echo: true\n  message: false\n  warning: false\nbibliography: references.bib\n---\n\n## Overview\n\nBuilding on our bivariate interpretation skills, this module extends logistic regression to realistic research scenarios involving multiple predictors and interaction effects. Real-world research rarely involves simple bivariate relationships. Instead, we need to control for multiple confounding variables and often discover that the effect of one variable depends on the level of another variable.\n\nIn this module, we will explore how controlling for additional variables changes our interpretation of individual predictors, understand when and why to include interaction terms in our models, learn to interpret complex conditional relationships step-by-step, and master both manual calculation and automated tools for understanding interactions. We will also discover how to visualize complex relationships using predicted probabilities and recognize when continuous versus dichotomous measures affect our analytical conclusions.\n\nBy the end of this module, you'll understand how multiple predictors work together in logistic regression, be able to interpret interaction effects manually and using specialized R tools, know how to visualize complex conditional relationships, and recognize the theoretical and practical considerations that guide interaction modeling decisions.\n\n## Models with Multiple Predictors\n\nIn our previous modules, we focused on bivariate relationships to build solid interpretive foundations. However, real research requires us to control for multiple potential confounding variables simultaneously. One of the most influential examples of multiple predictor logistic regression in political science comes from Fearon and Laitin's [-@fearon2003] groundbreaking study of civil war onset.\n\nFearon and Laitin argued that civil wars are not primarily caused by ethnic or religious grievances, but rather by conditions that favor insurgency: weak state capacity, difficult terrain, and economic underdevelopment. Their comprehensive model included multiple predictors to control for alternative explanations while testing their core theoretical arguments.\n\nHere we will loosely replicate their approach using the `peacesciencer` package and examine how our interpretation changes when we move from bivariate to multiple predictor models. First we will use the `peacesciencer` package to create a dataset similar to Fearon and Laitin's. Notice how you can add multiple predictors using the `add_*` functions, which automatically handle data cleaning and merging. Notice also that we are creating a dichotomous democracy measure (`democracy`) based on the continuous V-Dem `v2x_polyarchy` score, which we will use in our interaction models later.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(peacesciencer)\nlibrary(tidyverse)\n\n# Recreate the conflict dataset, adding a dichotomous democracy measure\nconflict_df <- create_stateyears(system = 'gw') |>\n  filter(year %in% c(1946:1999)) |>\n  add_ucdp_acd(type=c(\"intrastate\"), only_wars = FALSE) |>\n  add_democracy() |>\n  add_creg_fractionalization() |>\n  add_sdp_gdp() |>\n  add_rugged_terrain() |>\n  mutate(democracy = ifelse(v2x_polyarchy > 0.5, 1, 0)) |> # binary democracy measure\n  select(-ucdpongoing, -maxintensity, -conflict_ids, -sdpest) |>\n  drop_na() # need to drop NAs for logistic regression\n\nglimpse(conflict_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 6,091\nColumns: 17\n$ gwcode         <dbl> 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…\n$ statename      <chr> \"United States of America\", \"United States of America\",…\n$ year           <dbl> 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1…\n$ ucdponset      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ v2x_polyarchy  <dbl> 0.605, 0.587, 0.599, 0.599, 0.587, 0.602, 0.601, 0.594,…\n$ polity2        <dbl> 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,…\n$ xm_qudsest     <dbl> 1.259180, 1.259180, 1.252190, 1.252190, 1.270106, 1.259…\n$ ethfrac        <dbl> 0.2226323, 0.2248701, 0.2271561, 0.2294918, 0.2318781, …\n$ ethpol         <dbl> 0.4152487, 0.4186156, 0.4220368, 0.4255134, 0.4290458, …\n$ relfrac        <dbl> 0.4980802, 0.5009111, 0.5037278, 0.5065309, 0.5093204, …\n$ relpol         <dbl> 0.7769888, 0.7770017, 0.7770303, 0.7770729, 0.7771274, …\n$ wbgdp2011est   <dbl> 28.539, 28.519, 28.545, 28.534, 28.572, 28.635, 28.669,…\n$ wbpopest       <dbl> 18.744, 18.756, 18.781, 18.804, 18.821, 18.832, 18.848,…\n$ wbgdppc2011est <dbl> 9.794, 9.762, 9.764, 9.730, 9.752, 9.803, 9.821, 9.857,…\n$ rugged         <dbl> 1.073, 1.073, 1.073, 1.073, 1.073, 1.073, 1.073, 1.073,…\n$ newlmtnest     <dbl> 3.214868, 3.214868, 3.214868, 3.214868, 3.214868, 3.214…\n$ democracy      <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n```\n\n\n:::\n:::\n\n\nLet's now start out with a baseline model that includes multiple predictors. This model will allow us to see how controlling for other factors changes our interpretation of the relationship between democracy and conflict onset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the multiple predictor baseline model\nbaseline_model <- glm(ucdponset ~ v2x_polyarchy + newlmtnest + wbpopest + \n                     wbgdppc2011est + ethfrac + relfrac,\n                     data = conflict_df,\n                     family = \"binomial\")\n\n# Display the model summary\nsummary(baseline_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = ucdponset ~ v2x_polyarchy + newlmtnest + wbpopest + \n    wbgdppc2011est + ethfrac + relfrac, family = \"binomial\", \n    data = conflict_df)\n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)    -5.53894    1.38149  -4.009 6.09e-05 ***\nv2x_polyarchy  -0.54129    0.51336  -1.054 0.291690    \nnewlmtnest      0.12696    0.07256   1.750 0.080166 .  \nwbpopest        0.26463    0.07029   3.765 0.000167 ***\nwbgdppc2011est -0.36465    0.12180  -2.994 0.002755 ** \nethfrac         0.81768    0.38874   2.103 0.035427 *  \nrelfrac        -0.37589    0.41629  -0.903 0.366543    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1172.3  on 6090  degrees of freedom\nResidual deviance: 1113.6  on 6084  degrees of freedom\nAIC: 1127.6\n\nNumber of Fisher Scoring iterations: 7\n```\n\n\n:::\n:::\n\n\nThis baseline model reveals several important patterns. First, notice how some variables that might have been significant in bivariate models may lose significance when we control for other factors. This is a classic result in multiple regression: apparent relationships can disappear when we account for confounding variables.\n\nThe model tells us that population size (`wbpopest`) and GDP per capita (`wbgdppc2011est`) remain significant predictors even after controlling for other factors. Ethnic fractionalization (`ethfrac`) shows some evidence of increasing conflict risk, while the continuous democracy measure (`v2x_polyarchy`) is not statistically significant in this specification.\n\nThe key insight for interpretation is that each coefficient now represents the effect of that variable *holding all other variables constant*. When we say that the coefficient for GDP per capita is -0.365, we mean that a one-unit increase in log GDP per capita decreases the log-odds of conflict onset by 0.365 (or about 31% when we exponentiate the coefficient) controlling for democracy levels, terrain, population, ethnic fractionalization, and religious fractionalization*.\n\n::: {.callout-warning icon=false}\n## Your Turn!\n\nThe `peacesciencer` package provides multiple different measures of democracy, terrain and ethnic and religious divisions. Try running the baseline model using different combinations of these variables. How do the coefficients and significance levels change? What does this tell you about the importance of controlling for confounding variables in regression analysis?\n:::\n\n## Why Interaction Effects Matter in Conflict Research\n\n{{< video https://youtu.be/eb5lGVHHlY0?si=BCQJhZHezE9ihLg3 title='Effect Multipliers in Logistic Regression' >}}\n\nThe baseline model assumes that the effect of each predictor is the same regardless of the values of other predictors. This is called an **additive model** because the effects simply add up. But what if the effect of one variable depends on the level of another variable? What if mountainous terrain only increases conflict risk in non-democratic countries? What if economic development has a stronger peace-promoting effect in democratic societies?\n\nThese are questions about **interaction effects**, where the impact of one variable is **conditional** on the value of another variable. In conflict research, there are compelling theoretical reasons to expect such interactions. Democracy might provide institutional mechanisms for resolving grievances that would otherwise lead to violence. Democratic institutions might also change how other risk factors operate.\n\nConsider two theoretical scenarios:\n\n**Democracy and Terrain**: In non-democratic countries, mountainous terrain might facilitate insurgency because remote populations have no voice in government and rebels can hide in difficult terrain. In democratic countries, these same remote populations might have political representation and peaceful means of addressing grievances, reducing the conflict-promoting effect of terrain.\n\n**Democracy and Economic Development**: Economic growth might reduce conflict risk in all countries, but this effect might be amplified in democracies where the benefits of growth are more widely shared and people have more say about how their tax dollars are spent.\n\nTesting these theoretical expectations requires interaction terms in our logistic regression models. An interaction term allows the effect of one variable to vary depending on the level of another variable.\n\n## Interaction Effect #1: Democracy and Mountainous Terrain\n\nLet's start with the democracy-terrain interaction using our dichotomous democracy measure. This provides an excellent opportunity to understand interaction effects through manual calculation before moving to more complex tools.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit model with democracy-terrain interaction\nterrain_interaction_model <- glm(ucdponset ~ democracy * newlmtnest + wbpopest + \n                                wbgdppc2011est + ethfrac + relfrac,\n                                data = conflict_df,\n                                family = \"binomial\")\n\n# Display the model summary\nsummary(terrain_interaction_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = ucdponset ~ democracy * newlmtnest + wbpopest + \n    wbgdppc2011est + ethfrac + relfrac, family = \"binomial\", \n    data = conflict_df)\n\nCoefficients:\n                     Estimate Std. Error z value Pr(>|z|)    \n(Intercept)          -6.31995    1.40870  -4.486 7.24e-06 ***\ndemocracy             0.19601    0.48195   0.407 0.684224    \nnewlmtnest            0.18651    0.07909   2.358 0.018355 *  \nwbpopest              0.26762    0.07068   3.786 0.000153 ***\nwbgdppc2011est       -0.29958    0.11970  -2.503 0.012324 *  \nethfrac               0.78512    0.38998   2.013 0.044091 *  \nrelfrac              -0.33550    0.41231  -0.814 0.415809    \ndemocracy:newlmtnest -0.41501    0.20300  -2.044 0.040914 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1172.3  on 6090  degrees of freedom\nResidual deviance: 1106.5  on 6083  degrees of freedom\nAIC: 1122.5\n\nNumber of Fisher Scoring iterations: 7\n```\n\n\n:::\n:::\n\n\nThe interaction term `democracy:newlmtnest` has a coefficient of -0.415 and is statistically significant (p = 0.041). But what does this mean substantively?\n\nWith a dichotomous interaction variable like our democracy measure, we can calculate the conditional effects manually. The model equation is:\n\n$$\\text{logit}(p) = \\beta_0 + \\beta_1(\\text{democracy}) + \\beta_2(\\text{terrain}) + \\beta_3(\\text{democracy} \\times \\text{terrain}) + \\text{other controls}$$\n\nThis gives us two different equations depending on the democracy level:\n\n**For non-democratic countries** (democracy = 0):\n$$\\text{logit}(p) = \\beta_0 + \\beta_2(\\text{terrain}) + \\text{other controls}$$\n\nThe effect of terrain is simply $\\beta_2 = 0.187$.\n\n**For democratic countries** (democracy = 1):\n$$\\text{logit}(p) = \\beta_0 + \\beta_1 + (\\beta_2 + \\beta_3)(\\text{terrain}) + \\text{other controls}$$\n\nThe effect of terrain is $\\beta_2 + \\beta_3 = 0.187 + (-0.415) = -0.228$.\n\nHere is how it would look if we did that with R code. We can also \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(marginaleffects)\nlibrary(broom)\n\nconditional_effects_terrain <- slopes(terrain_interaction_model, \n                                      variables = \"newlmtnest\",\n                                      by = \"democracy\",\n                                      type = \"link\") |>\n  tidy() |> # convert to tidy format\n  mutate(odds.ratio = exp(estimate)) |> # add column with odds ratios\n  select(\n    term:std.error, \n    conf.low:odds.ratio\n  )\n\nconditional_effects_terrain\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term       democracy estimate std.error conf.low conf.high odds.ratio\n  <chr>          <dbl>    <dbl>     <dbl>    <dbl>     <dbl>      <dbl>\n1 newlmtnest         0    0.187    0.0791   0.0315     0.342      1.21 \n2 newlmtnest         1   -0.228    0.189   -0.599      0.142      0.796\n```\n\n\n:::\n:::\n\n\n::: {.callout-important}\n## Understanding the Code\n\nThe `slopes()` function in marginaleffects can calculate marginal effects on different scales. By default, it uses `type = \"response\"`, which gives us marginal effects on the probability scale that show how much the probability of conflict changes per unit increase in terrain. These effects are typically very small because probabilities are constrained between 0 and 1.\n\nWhen we specify `type = \"link\"`, we get marginal effects on the log-odds scale instead. This matches the scale of our model coefficients and our manual calculations above. Using type = \"link\" is particularly helpful for understanding interactions because it directly corresponds to the coefficients we see in our model summary, making it easier to connect the automated results to the underlying mathematical relationships.\n\nAfter we run the `slopes()` function, we use `tidy()` to convert the results into a tidy format that is easier to read and manipulate. We then calculate the odds ratios by exponentiating the estimates, which allows us to interpret the effects in terms of odds rather than log-odds. Then we select only the relevant columns for clarity.\n:::\n\nThese results reveal a fascinating pattern! In non-democratic countries, mountainous terrain increases the odds of conflict onset by about 21% for each unit increase in terrain roughness (odds ratio = 1.206). However, in democratic countries, mountainous terrain actually decreases the odds of conflict onset by about 20% for each unit increase (odds ratio = 0.796).\n\nThis interaction suggests that democracy fundamentally changes how terrain affects conflict risk. In authoritarian systems, difficult terrain may indeed facilitate insurgency by providing rebels with safe havens and making government control difficult. In democratic systems, perhaps the same geographical isolation is less problematic because remote populations have political voice and peaceful means of addressing grievances.\n\n::: {.callout-warning icon=false}\n## Your Turn!\n\nNow practice interpreting interaction effects by examining the democracy main effect:\n\n1. Calculate the effect of democracy when terrain = 0 using the model coefficients\n2. Calculate the effect of democracy when terrain = 1 (one standard deviation above mean)\n3. Convert both to odds ratios and interpret the results\n4. What does this tell us about when democracy has stronger or weaker effects on conflict risk?\n\nRemember: the interaction works both ways! If terrain's effect depends on democracy, then democracy's effect also depends on terrain.\n:::\n\n## Interaction Effect #2: Democracy and Economic Development\n\nOur second interaction examines how democracy moderates the relationship between economic development and conflict risk. For this analysis, we'll use the continuous democracy measure (`v2x_polyarchy`) to illustrate why we need more sophisticated tools when dealing with continuous interaction variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit model with continuous democracy-wealth interaction\nwealth_interaction_model <- glm(ucdponset ~ v2x_polyarchy * wbgdppc2011est + newlmtnest + \n                               wbpopest + ethfrac + relfrac,\n                               data = conflict_df,\n                               family = \"binomial\")\n\n# Display the model summary\nsummary(wealth_interaction_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = ucdponset ~ v2x_polyarchy * wbgdppc2011est + newlmtnest + \n    wbpopest + ethfrac + relfrac, family = \"binomial\", data = conflict_df)\n\nCoefficients:\n                             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)                  -8.34699    1.77914  -4.692 2.71e-06 ***\nv2x_polyarchy                 9.39357    4.04517   2.322 0.020224 *  \nwbgdppc2011est               -0.05136    0.17087  -0.301 0.763742    \nnewlmtnest                    0.15972    0.07470   2.138 0.032496 *  \nwbpopest                      0.26812    0.06999   3.831 0.000128 ***\nethfrac                       0.75002    0.38459   1.950 0.051155 .  \nrelfrac                      -0.24191    0.41891  -0.577 0.563613    \nv2x_polyarchy:wbgdppc2011est -1.13001    0.46270  -2.442 0.014598 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1172.3  on 6090  degrees of freedom\nResidual deviance: 1107.3  on 6083  degrees of freedom\nAIC: 1123.3\n\nNumber of Fisher Scoring iterations: 8\n```\n\n\n:::\n:::\n\n\nThe interaction term `v2x_polyarchy:wbgdppc2011est` has a coefficient of -1.130 and is statistically significant (p = 0.015). This negative coefficient suggests that democracy amplifies the conflict-reducing effect of economic development. But with a continuous moderator variable, we can't simply calculate \"democracy = 0\" and \"democracy = 1\" effects as we did before.\n\nThis is where the `marginaleffects` package becomes invaluable. We can specify `at = list()` to calculate the conditional effect of economic development at different levels of democracy, taking into account the continuous nature of our democracy measure:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_effects_wealth <- slopes(wealth_interaction_model, \n                       variables = \"wbgdppc2011est\",\n                       newdata = datagrid(v2x_polyarchy = c(0.1, 0.3, 0.5, 0.7, 0.9)),\n                       type = \"link\") |>  \n  tidy() |> \n  mutate(odds.ratio = exp(estimate)) |> \n  select(v2x_polyarchy, estimate, std.error, conf.low, conf.high, odds.ratio)\n\n\nconditional_effects_wealth\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  v2x_polyarchy estimate std.error conf.low conf.high odds.ratio\n          <dbl>    <dbl>     <dbl>    <dbl>     <dbl>      <dbl>\n1           0.1   -0.164     0.141   -0.440     0.112      0.848\n2           0.3   -0.390     0.117   -0.620    -0.161      0.677\n3           0.5   -0.616     0.157   -0.925    -0.308      0.540\n4           0.7   -0.842     0.230   -1.29     -0.391      0.431\n5           0.9   -1.07      0.314   -1.68     -0.454      0.344\n```\n\n\n:::\n:::\n\n\nThese results reveal how democracy progressively amplifies the peace-promoting effects of economic development. In highly authoritarian countries (polyarchy = 0.1), economic development has a modest negative effect on conflict risk. As democracy levels increase, this peace-promoting effect becomes much stronger. In highly democratic countries (polyarchy = 0.9), the conflict-reducing effect of economic development is substantially amplified.\n\nThe theoretical interpretation is compelling: economic development may reduce conflict risk in all political systems, but democratic institutions help ensure that the benefits of growth are more widely shared and that economic grievances can be addressed through peaceful political processes rather than violence.\n\n## Visualizing Interaction Effects\n\nWhile manual calculations and marginal effects tables provide precise numerical results, visualization often communicates interaction patterns more effectively. The `marginaleffects` package includes excellent plotting capabilities that integrate seamlessly with our models.\n\nLet's create interaction plots for both of our democracy interaction models using the `plotslopes()` functions. First we'll visualize the terrain interaction:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nterrain_plot <- plot_slopes(terrain_interaction_model, \n                           variables = \"newlmtnest\", \n                           condition = \"democracy\") +\n  labs(title = \"Effect of Terrain on Conflict Risk by Democracy Level\",\n       subtitle = \"Terrain increases conflict risk more in non-democratic countries\",\n       x = \"Democracy Level\", \n       y = \"Marginal Effect of Terrain\") +\n  theme_minimal()\n\nterrain_plot\n```\n\n::: {.cell-output-display}\n![](module-5.4_files/figure-html/interaction_plots-1.png){width=672}\n:::\n:::\n\n\nHere we see how the marginal effect (the increase in conflict risk per unit increase in terrain) varies by democracy level. The plot clearly shows that mountainous terrain increases conflict risk in non-democratic countries more than in democratic ones. The confidence intervals also illustrate the uncertainty around these estimates, which is important when considering the reliability of our results.\n\nNow let's visualize the wealth interaction:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwealth_plot <- plot_slopes(wealth_interaction_model,\n                          variables = \"wbgdppc2011est\",\n                          condition = \"v2x_polyarchy\") +\n  labs(title = \"Effect of Economic Development on Conflict Risk by Democracy Level\",\n       subtitle = \"Democracy amplifies the peace-promoting effects of economic development\",\n       x = \"Democracy Level (Polyarchy)\", \n       y = \"Marginal Effect of GDP per Capita\") +\n  theme_minimal()\n\nprint(wealth_plot)\n```\n\n::: {.cell-output-display}\n![](module-5.4_files/figure-html/wealth_interaction_plot-1.png){width=672}\n:::\n:::\n\n\nHere we see how the marginal effect of economic development on conflict risk varies across different levels of democracy. The plot illustrates that as democracy increases, the peace-promoting effect of economic development becomes stronger, confirming our earlier interpretation.\n\nWe can also visualize these relationships using predicted probabilities across different scenarios using the `plot_predictions()` function. First, let's visualize the terrain interaction:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictions_terrain <- plot_predictions(terrain_interaction_model, \n                                      condition = c(\"newlmtnest\", \"democracy\")) +\n  labs(title = \"Predicted Probability of Conflict Onset\",\n       subtitle = \"Democracy changes how terrain affects conflict risk\") +\n  theme_minimal()\n\npredictions_terrain\n```\n\n::: {.cell-output-display}\n![](module-5.4_files/figure-html/predicted_probability_terrain-1.png){width=672}\n:::\n:::\n\n\nNow let's visualize the wealth interaction:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictions_wealth <- plot_predictions(wealth_interaction_model,\n                                     condition = c(\"wbgdppc2011est\", \"v2x_polyarchy\"),\n                                     at = list(v2x_polyarchy = c(0.2, 0.8))) +\n  labs(title = \"Predicted Probability of Conflict Onset\",\n       subtitle = \"Economic development effects vary by democracy level\") +\n  theme_minimal()\n\npredictions_wealth\n```\n\n::: {.cell-output-display}\n![](module-5.4_files/figure-html/predicted_probability_wealth-1.png){width=672}\n:::\n:::\n\n\nThese visualizations make the interaction patterns immediately apparent. They show not just the direction and significance of interactions, but also their practical magnitude across realistic ranges of the variables.\n\n::: {.callout-warning icon=false}\n## Your Turn!\n\nCreate your own interaction visualization by:\n\n1. Choosing one of our interaction models\n2. Using `plot_predictions()` to show predicted probabilities across different combinations of the interacting variables\n3. Experimenting with the `at` argument to focus on specific values of interest\n4. Adding informative titles and labels to make your plot publication-ready\n\nThink about what story your visualization tells. How would you explain this interaction to a policy audience unfamiliar with statistical modeling?\n:::\n\n## Model Comparison and Selection Considerations\n\nWhen should we include interaction terms in our models? This decision should be guided by both theoretical considerations and empirical evidence. Interactions should be theoretically motivated rather than the result of fishing expeditions through possible variable combinations.\n\nIn our conflict example, both interactions have strong theoretical foundations. The democracy-terrain interaction tests whether democratic institutions provide alternative channels for addressing grievances that might otherwise lead to insurgency in remote areas. The democracy-wealth interaction examines whether democratic institutions help translate economic development into political stability more effectively than authoritarian institutions.\n\nLet's compare our models to see how interactions affect overall model fit:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare model fit using AIC\nmodels_comparison <- data.frame(\n  Model = c(\"Baseline\", \"Democracy × Terrain\", \"Democracy × Wealth\"),\n  AIC = c(AIC(baseline_model), AIC(terrain_interaction_model), AIC(wealth_interaction_model)),\n  Deviance = c(deviance(baseline_model), deviance(terrain_interaction_model), deviance(wealth_interaction_model))\n)\n\nmodels_comparison\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Model      AIC Deviance\n1            Baseline 1127.636 1113.636\n2 Democracy × Terrain 1122.476 1106.476\n3  Democracy × Wealth 1123.313 1107.313\n```\n\n\n:::\n:::\n\n\nBoth models reduce the AIC compared to the baseline model. We can confirm this using likelihood ratio tests, which compare nested models to see if the additional parameters significantly improve fit:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Test significance of interaction terms using likelihood ratio tests\nlibrary(lmtest)\n\n# Test terrain interaction\nlrtest(baseline_model, terrain_interaction_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio test\n\nModel 1: ucdponset ~ v2x_polyarchy + newlmtnest + wbpopest + wbgdppc2011est + \n    ethfrac + relfrac\nModel 2: ucdponset ~ democracy * newlmtnest + wbpopest + wbgdppc2011est + \n    ethfrac + relfrac\n  #Df  LogLik Df  Chisq Pr(>Chisq)   \n1   7 -556.82                        \n2   8 -553.24  1 7.1604   0.007453 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# For wealth interaction, need to adjust baseline model for fair comparison\nbaseline_continuous <- glm(ucdponset ~ v2x_polyarchy + newlmtnest + wbpopest + \n                          wbgdppc2011est + ethfrac + relfrac,\n                          data = conflict_df, family = \"binomial\")\n\nlrtest(baseline_continuous, wealth_interaction_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio test\n\nModel 1: ucdponset ~ v2x_polyarchy + newlmtnest + wbpopest + wbgdppc2011est + \n    ethfrac + relfrac\nModel 2: ucdponset ~ v2x_polyarchy * wbgdppc2011est + newlmtnest + wbpopest + \n    ethfrac + relfrac\n  #Df  LogLik Df  Chisq Pr(>Chisq)  \n1   7 -556.82                       \n2   8 -553.66  1 6.3229    0.01192 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe way we read this results is that if the p-value is less than 0.05, then we can conclude that the interaction term significantly improves model fit compared to the baseline model. If the p-value is greater than 0.05, then we cannot conclude that the interaction term significantly improves model fit.\n\nBased on these tests, we can conclude that both interaction terms significantly improve model fit. However, remember that model fit alone should not drive interaction decisions. The theoretical motivation for expecting conditional effects should be the primary consideration.\n\n## Summary\n\nThis module has equipped you with essential skills for handling realistic logistic regression analyses involving multiple predictors and interaction effects. We discovered how moving from bivariate to multiple predictor models changes coefficient interpretation by controlling for confounding variables. We learned to identify when interaction effects are theoretically justified and how they allow the effect of one variable to depend on another. We mastered both manual calculation techniques for simple interactions and automated tools for complex conditional relationships. Most importantly, we developed skills in visualizing and communicating complex interaction patterns to diverse audiences.\n\nThe Fearon-Laitin replication demonstrated how democracy can fundamentally alter the relationships between other variables and conflict risk. Mountainous terrain appears to promote conflict only in non-democratic settings, while economic development has stronger peace-promoting effects in democratic contexts. These findings illustrate why interaction effects are crucial for understanding real-world political phenomena.\n\nOur progression from manual calculation with dichotomous variables to automated tools with continuous variables provides a solid foundation for tackling any interaction scenario. The visualization techniques we learned help communicate complex statistical relationships to policy audiences who need to understand not just whether interactions exist, but what they mean in practice.\n\n\n\n",
    "supporting": [
      "module-5.4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}